# Generated by Django 3.2.6 on 2021-08-06 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_ticket_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='content',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket.state', verbose_name='Статус'),
        ),
    ]
